<?php
include 'dbConnect.php';
echo "Creating Tables";


function runquery($connection, $query, $tablename)
{
  echo "<br>Creating " . $tablename . " table...<br>";
  try {
    $stmt = $connection->query($query);
    echo "  Succesfully<br>";
  } catch (mysqli_sql_exception $e) {
    echo "  Error creating " . $tablename . " table..." . $e->getMessage() . "<br>";
  }
}

runquery($conn, "
      CREATE TABLE IF NOT EXISTS CLASSROOM(
        CLASSROOM_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        FLOOR_NUMBER VARCHAR(15) NOT NULL,
        ROOM_NUMBER INT NOT NULL,
        CAPACITY INT NOT NULL,
        DATE_CREATED DATE NOT NULL DEFAULT CURRENT_DATE
      );
    ", "Classroom");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS TIMESLOT(
        SLOT_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        START_TIME TIME NOT NULL,
        END_TIME TIME NOT NULL,
        ISBREAK BOOLEAN NOT NULL DEFAULT FALSE,
        DATE_CREATED DATE NOT NULL DEFAULT CURRENT_DATE
      );
    ", "Timeslot");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS USER(
        USERNAME VARCHAR(31) NOT NULL PRIMARY KEY,
        PASSWORD VARCHAR(255) NOT NULL,
        DATE_CREATED DATE NOT NULL DEFAULT CURRENT_DATE,
        ISBLOCKED BOOLEAN DEFAULT FALSE,
        ISDELETED BOOLEAN DEFAULT FALSE,
        LOGIN_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        LOGIN_IP VARCHAR(15)
      );
    ", "User");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS DEPARTMENT(
        DEPARTMENT_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        USERNAME VARCHAR(31),
        LONG_NAME VARCHAR(63) NOT NULL,
        SHORT_NAME VARCHAR(31) NOT NULL,
        DATE_CREATED DATE NOT NULL DEFAULT(CURRENT_DATE),

        CONSTRAINT fk_usrnm_deptTbl
        FOREIGN KEY (USERNAME) 
        REFERENCES USER(USERNAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE
      );
    ", "Department");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS TEACHER(
        TEACHER_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        DEPARTMENT_ID INT  NOT NULL,
        FIRST_NAME VARCHAR(15) NOT NULL,
        LAST_NAME VARCHAR(15) NOT NULL,
        ISPARTTIME BOOLEAN NOT NULL DEFAULT(0),
        DATE_CREATED DATE NOT NULL DEFAULT(CURRENT_DATE),

        CONSTRAINT fk_deptId_tchrTbl
        FOREIGN KEY (DEPARTMENT_ID) 
        REFERENCES DEPARTMENT(DEPARTMENT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
      );
    ", "Teacher");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS AVAILABILITY(
        TEACHER_ID INT NOT NULL,
        SLOT_ID INT NOT NULL,
        STATUS ENUM('AVAILABLE','NOT AVAILABLE') DEFAULT 'AVAILABLE',

        PRIMARY KEY(TEACHER_ID, SLOT_ID),

        CONSTRAINT fk_tchrId_avlbtTbl
        FOREIGN KEY (TEACHER_ID) 
        REFERENCES TEACHER(TEACHER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        CONSTRAINT fk_slotId_avlbtTbl
        FOREIGN KEY (SLOT_ID) 
        REFERENCES TIMESLOT(SLOT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
      );
    ", "Availability");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS PROGRAMME(
        PROGRAMME_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        DEPARTMENT_ID INT,
        LONG_NAME VARCHAR(63) NOT NULL,
        SHORT_NAME VARCHAR(15) NOT NULL,
        DIVISION_COUNT INT NOT NULL DEFAULT(0),
        DATE_CREATED DATE NOT NULL DEFAULT(CURRENT_DATE),

        CONSTRAINT fk_deptId_pgrmTbl 
        FOREIGN KEY (DEPARTMENT_ID) 
        REFERENCES DEPARTMENT(DEPARTMENT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
      );
    ", "Programme");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS DIVISION(
        DIVISION_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        PROGRAMME_ID INT,
        NAME CHAR NOT NULL,
        STUDENT_COUNT INT NOT NULL DEFAULT(0),
        DATE_CREATED DATE NOT NULL DEFAULT(CURRENT_DATE),

        CONSTRAINT fk_pgrmId_dvsnTbl 
        FOREIGN KEY (PROGRAMME_ID) 
        REFERENCES PROGRAMME(PROGRAMME_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
      );
    ", "Division");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS COURSE(
        COURSE_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        PROGRAMME_ID INT,
        LONG_NAME VARCHAR(63) NOT NULL,
        SHORT_NAME VARCHAR(15) NOT NULL,
        WEEKLY_LECTURES INT NOT NULL,
        ISPRACTICAL BOOLEAN DEFAULT 0,
        DATE_CREATED DATE NOT NULL DEFAULT(CURRENT_DATE),

        CONSTRAINT fk_pgrmId_crseTbl 
        FOREIGN KEY (PROGRAMME_ID) 
        REFERENCES PROGRAMME(PROGRAMME_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
      );
    ", "Course");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS GIVEN(
        SLOT_ID INT NOT NULL,
        CLASSROOM_ID INT,
        DIVISION_ID INT,

        PRIMARY KEY(SLOT_ID, CLASSROOM_ID, DIVISION_ID),

        CONSTRAINT fk_slotId_gvenTbl
        FOREIGN KEY (SLOT_ID) 
        REFERENCES TIMESLOT(SLOT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        CONSTRAINT fk_clsrmId_gvenTbl
        FOREIGN KEY (CLASSROOM_ID) 
        REFERENCES CLASSROOM(CLASSROOM_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        CONSTRAINT fk_dvsnId_gvenTbl
        FOREIGN KEY (DIVISION_ID) 
        REFERENCES DIVISION(DIVISION_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
      );
    ", "Given");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS TEACHES(
        TEACHER_ID INT,
        COURSE_ID INT,
        DIVISION_ID INT,
        LECTURE_COUNT INT NOT NULL DEFAULT(0),
        DATE_CREATED DATE NOT NULL DEFAULT(CURRENT_DATE),
        
        PRIMARY KEY(TEACHER_ID,COURSE_ID,DIVISION_ID),

        CONSTRAINT fk_tchrId_tchsTbl 
        FOREIGN KEY (TEACHER_ID) 
        REFERENCES TEACHER(TEACHER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        CONSTRAINT fk_crseId_tchsTbl 
        FOREIGN KEY (COURSE_ID) 
        REFERENCES COURSE(COURSE_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        CONSTRAINT fk_dvsn_tchsTbl 
        FOREIGN KEY (DIVISION_ID) 
        REFERENCES DIVISION(DIVISION_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE

      );
    ", "Teaches");

runquery($conn, "
      CREATE TABLE IF NOT EXISTS TIMETABLE(
        COURSE_ID INT,
        DIVISION_ID INT,
        CLASSROOM_ID INT,
        SLOT_ID INT,
        TEACHER_ID INT,
        ACADEMIC_YEAR VARCHAR(7) NOT NULL,
        SEMESTER VARCHAR(4) NOT NULL,
        DATE_CREATED DATE NOT NULL DEFAULT(CURRENT_DATE),

        PRIMARY KEY(COURSE_ID, DIVISION_ID, CLASSROOM_ID, SLOT_ID, TEACHER_ID, ACADEMIC_YEAR, SEMESTER),

        CONSTRAINT fk_crseId_tTbl 
        FOREIGN KEY (COURSE_ID) 
        REFERENCES COURSE(COURSE_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        CONSTRAINT fk_dvsnId_tTbl 
        FOREIGN KEY (DIVISION_ID) 
        REFERENCES DIVISION(DIVISION_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        CONSTRAINT fk_clsrmId_tTbl 
        FOREIGN KEY (CLASSROOM_ID) 
        REFERENCES CLASSROOM(CLASSROOM_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        CONSTRAINT fk_slotId_tTbl 
        FOREIGN KEY (SLOT_ID) 
        REFERENCES TIMESLOT(SLOT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        CONSTRAINT fk_tchrId_tTbl 
        FOREIGN KEY (TEACHER_ID) 
        REFERENCES TEACHER(TEACHER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
      );
    ", "Timetable");






